Create Specs.md
devskrate/devskrate1.0 pull request #29
Opened 2020-05-26 16:54 UTC by mohitindukuri

2020-05-26 16:57 UTC, puneethkanna commented
Change it to the post layout

2020-05-27 06:20 UTC, SriSatyaLokesh commented on _posts/2020-05-26-realmetv-specs.md
> +**Realme Smart TV: Remote**
replace all these bold to ####

2020-05-27 06:20 UTC, SriSatyaLokesh requested changes
please chane heading formats

2020-05-27 07:21 UTC, puneethkanna commented on _posts/2020-05-26-realmetv-specs.md
> +**Price and Availability:**
Change the bold headings to ####(h4) headings

2020-05-27 08:45 UTC, mohitindukuri commented on _posts/2020-05-26-realmetv-specs.md
> +**Realme Smart TV: Remote**
ok bro

2020-05-27 09:09 UTC, merged